#!/bin/bash

if [ -z "$1" ]
  then
    echo "Error: USAGE: ./create_application <app_name>"
    exit 1
fi


app_name=$1

docker build -t $app_name"_base" \
    --build-arg UID=$(id -u) \
    --build-arg GID=$(id -g) \
    .

docker rm -f $app_name"_app"

docker run -d -v \
    $(pwd):/var/www/html \
    -p 80:80 \
    --name=$app_name"_app" \
    $app_name"_base"

docker exec -it $app_name"_app" bash -c "chmod -R 775 /var/www/html/{*,.*}"
docker exec -it $app_name"_app" bash -c "chown -R www-data:www-data /var/www/html/{*,.*}"
docker exec -it $app_name"_app" bash -c "composer create-project laravel/laravel $app_name"
docker exec -it $app_name"_app" bash -c "mv $app_name/{*,.*} ."
docker exec -it $app_name"_app" bash -c "chmod -R 775 /var/www/html/{*,.*}"
docker exec -it $app_name"_app" bash -c "chown -R www-data:www-data /var/www/html/{*,.*}"
